[package]
name = "pbus_timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path = "../utility" }
pbus_config_handler = { path = "../pbus_config_handler" }